name: daisy
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  sentry_dio: ^8.9.0
  sentry_flutter: ^8.9.0
  share_plus: ^10.1.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  wolt_modal_sheet: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.7.0
  build_runner: ^2.4.13
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/image/app_logo.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/flag/
    - assets/icon/
    - assets/image/
    - assets/video/
    - assets/translation/
